/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package service;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author roland
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 1.x JSON provider:
        try {
            Class jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(service.CoopAddlAddressFacadeREST.class);
        resources.add(service.CoopAddlContactInfoFacadeREST.class);
        resources.add(service.CoopApplicantFacadeREST.class);
        resources.add(service.CoopAwardsFacadeREST.class);
        resources.add(service.CoopBizInfoFacadeREST.class);
        resources.add(service.CoopEducInfoFacadeREST.class);
        resources.add(service.CoopEmplDtlFacadeREST.class);
        resources.add(service.CoopKinFacadeREST.class);
        resources.add(service.CoopKinshipFacadeREST.class);
        resources.add(service.CoopMemSkillFacadeREST.class);
        resources.add(service.CoopMemberFacadeREST.class);
        resources.add(service.CoopOrgUnitFacadeREST.class);
        resources.add(service.CoopSkillFacadeREST.class);
    }
    
}
